### ISSUE TITLE
Android R8 issue with Ser

### ISSUE THREAD

**Issue by wbervoets** [ThreeTen/threetenbp#120]
Hello,

When using https://github.com/JakeWharton/ThreeTenABP on Android (which depends on threetenbp) we are having an issue that Android Release builds that are minimized using Google R8 throws an exception due to the default constructor of the class org.threeten.bp.Ser being removed by R8

Can you add a R8 proguard file in the library so R8 will not perform the optimization?

`
-keepclassmembers class org.threeten.bp.Ser {
    <init>();
}
`

Cfr: https://github.com/JakeWharton/ThreeTenABP/issues/122

**Comment by jodastephen** [comment]
Feel free to raise a PR
