### ISSUE TITLE
Sometimes unable to serialize OffsetDateTime Object in Android

### ISSUE THREAD

**Issue by msbouchedid** [ThreeTen/threetenbp#122]
Seeing the following weird error on Android. This only occurs in some cases when the object gets deserialized / serialized going through an android bundle workflow. Once the activity is reset (portrait to landscape) it needs to recreate the object. 

OffsetDateTime implements Serializable so this shouldn't be a problem... wondering if anyone else ran into this?

java.lang.RuntimeException: Parcelable encountered IOException reading a Serializable object (name = org.threeten.bp.OffsetDateTime)

Parcelable encountered IOException reading a Serializable object (name = org.threeten.bp.OffsetDateTime)

Caused by java.io.InvalidClassException
g.c.a.a; no valid constructor

**Comment by msbouchedid** [comment]
When I've seen this issue before on Android, it usually is because it expects the class to have an empty argument constructor such as 

public OffsetDateTime() {
}

This is so that the serializable can call the constructor to build the object when recreating it.

**Comment by JakeWharton** [comment]
Are you sure `g.c.a.a` maps to `OffsetDateTime` and not `Ser`? We just fixed a serialization issue in #120 but it hasn't been released yet.

**Comment by msbouchedid** [comment]
I'm not sure what Ser is. 

Update: I was able to recreate this issue with proguard enabled on my device. I enter the activity and rotate the device so the activity gets recreated.

The fix you linked me to might potentially fix this, I'd like to test it out

**Comment by msbouchedid** [comment]
Update: 

I was able to solve the issue by adding the following to the proguard rules file:

##---------------proguard configuration for OffsetDateTime  ----------
-keepclassmembers class org.threeten.bp.** implements java.io.Serializable {
  private static final java.io.ObjectStreamField[] serialPersistentFields;
  private void writeObject(java.io.ObjectOutputStream);
  private void readObject(java.io.ObjectInputStream);
  java.lang.Object writeReplace();
  java.lang.Object readResolve();
}
##---------------End: proguard configuration for OffsetDateTime  ----------

This was taken from this project: https://github.com/JakeWharton/ThreeTenABP.

This issue is now resolved. 

Thanks

**Comment by jodastephen** [comment]
Closing as per request above.
