### ISSUE TITLE
Provide package-list with Javadoc

### ISSUE THREAD

**Issue by mvglasow** [ThreeTen/threetenbp#131]
I am using ThreeTenBp in my project, and some of its classes are exposed as function arguments. In order to incorporate the ThreeTenBp Javadoc documentation into mine (i.e. link from there), the Javadoc tool requires a file named `package-list` to be present at the main Javadoc path. However, https://www.threeten.org/threetenbp/apidocs/package-list gives a 404 error, hence Javadoc integration does not work.

**Comment by jodastephen** [comment]
Fixed by https://github.com/ThreeTen/threeten.github.io/commit/d01f336f443b17686e5cb1ce05cb615bcf0a6f43
