### ISSUE TITLE
DayTime(int day, int hour, int minute)-> DayTime(MONDAY,12,00) is giving DayTime{time=0:00PM, day=MONDAY}

### ISSUE THREAD

**Issue by ismaielsharif** [ThreeTen/threetenbp#132]
i'm trying to get DayTime object from Calander instance(Java & Kotlin). but threetenbp lib is giving me  wrong results when hours are 12:00

 var dayTime = DayTime(cal.get(Calendar.DAY_OF_WEEK), 12, 0)
result : DayTime{time=0:12PM, day=MONDAY}

anyone who face this issue..

**Comment by jodastephen** [comment]
There is no `DayTime` class in ThreeTenBP. Maybe you wanted ThreeTen-Extra?

When investigating this, bear in mind that `cal.get(Calendar.DAY_OF_WEEK)` returns different values for the days of the week from `java.time.*`. `Calendar` has `MONDAY=2`, but `java.time.*` has `MONDAY=1`.
