### ISSUE TITLE
org.threeten.bp.format.DateTimeParseException: Text 'Sat Sep 19 2020 07:14 AM PDT' could not be parsed at index 25

### ISSUE THREAD

**Issue by jchio001** [ThreeTen/threetenbp#134]
(Note: filing this issue here based off of https://github.com/JakeWharton/ThreeTenABP/issues/81)

I'm using an Android port of the library (https://github.com/JakeWharton/ThreeTenABP) to parse a `String` like `Sat Sep 19 2020 07:14 AM PDT` into a `ZonedDateTime`. My code looks roughly like:
```
val formatter = DateTimeFormatter.ofPattern(
  "EEE MMM dd yyyy hh:mm a zzz",
  Locale.US
)

return ZonedDateTime.parse(
  "Sat Sep 19 2020 07:14 AM PDT",
  formatter
)

```

However, parsing this timestamp leads to the following crash:
```
Caused by: org.threeten.bp.format.DateTimeParseException: Text 'Sat Sep 19 2020 07:14 AM PDT' could not be parsed at index 25
at org.threeten.bp.format.DateTimeFormatter.parseToBuilder(DateTimeFormatter.java:1588)
at org.threeten.bp.format.DateTimeFormatter.parse(DateTimeFormatter.java:1491)
at org.threeten.bp.ZonedDateTime.parse(ZonedDateTime.java:562)
```

The interesting thing is that if I were to do the same exact parsing using `java.time`, I'm able to successfully parse the `String` into a `ZonedDatedTime`. Here's some sample code demonstrating this: https://www.onlinegdb.com/HkqpJlVHv.

**Comment by jodastephen** [comment]
This must be a problem on Android which I can't really help with. The code works fine on JDK6, 8, 11 and at https://www.onlinegdb.com/HkqpJlVHv
