### ISSUE TITLE
Wrong OffsetDateTime

### ISSUE THREAD

**Issue by karun2189** [ThreeTen/threetenbp#138]
Hi, 

OffsetDateTime.now() is changing. 

LogUtils.e("Converter","Before Current Offset : ${OffsetDateTime.now()}")
val oTs = OffsetDateTime.now()?.format(DateTimeFormatter.ISO_ZONED_DATE_TIME)
LogUtils.e("Converter","Offset to String : $oTs")
LogUtils.e("Converter","After Current Offset : ${OffsetDateTime.now()}")

Before Current Offset : **2020-10-17T10:55:33.559+05:30**
Offset to String : 2020-10-17T05:25:33.561Z
After Current Offset : **2020-10-17T05:25:33.564Z**

Any help?

**Comment by jodastephen** [comment]
I can't reproduce this using JDK 6. I suspect it is something weird with the initialization phase on Android.
