### ISSUE TITLE
TZDB Update workflow is broken

### ISSUE THREAD

**Issue by BaloghTamas** [ThreeTen/threetenbp#156]
TZDB auto-update Github Actions Workflow is broken, and not passing for a month now. 

The issue is that the referenced tzdb repo started to use [tag names](https://github.com/JodaOrg/tz/tags) that are not exactly equal to the TZDB file name, previously it had used branch names like `2021a`, but now it uses branch names like `2021afork1` which breaks the workflow that expect to use tag name as a file name to copy.

```
Run mkdir -p src/tzdb/${LATEST_TZDB}
cp: cannot stat 'target/tz/tzdata2021bfork3-rearguard.dir/.': No such file or directory
Error: Process completed with exit code 1.
```

To fix the issue, the workflow should be updated to properly extract TZDB file name from the branch name.

**Comment by BaloghTamas** [comment]
Also it seems like that for the latest version, there are no rearguard files generated, at least I see the following files created
```
drwxr-xr-x  2 runner docker   4096 Nov  8 09:22 tzdata2021b-24-g7ad6c47-rearguard.dir
-rw-r--r--  1 runner docker 421926 Nov  8 09:22 tzdata2021b-24-g7ad6c47-rearguard.tar.gz
```

And then the process failes with error code:
```
cp: cannot stat 'target/tz/tzdata2021efork-rearguard.dir/.': No such file or directory
```

**Comment by jodastephen** [comment]
Release 1.5.2 with updated time zone data now available.

**Comment by BaloghTamas** [comment]
Thanks, but I think the auto update is still broken. I guess it would worth fixing it if this is possible with the new fork way. Or if fixing is not feasible, at least it could detect when a new version is available and open an issue for it.

**Comment by jodastephen** [comment]
The release was done with the auto-update. The failure is misleading and has also been addressed.
