### ISSUE TITLE
Time format in japanese is not optimal

### ISSUE THREAD

**Issue by kushalkadaba** [ThreeTen/threetenbp#159]
Time format is not localized in Japanese.

Incorrect: 14:30

Proposed: 14時30分

Code:

        final DateTimeFormatter dateTimeFormatter = new DateTimeFormatterBuilder()
                .append(DateTimeFormatter.ofLocalizedTime(FormatStyle.SHORT))
                .toFormatter(Locale.JAPAN);
        System.out.println(dateTimeFormatter.format(LocalDateTime.now()));

        DateTimeFormatter localizedFormatter = DateTimeFormatter.ofPattern("h:mm", Locale.JAPAN);
        System.out.println(LocalDateTime.now().toLocalTime().format(localizedFormatter));`

Output: 
11:31
11:31

**Comment by jodastephen** [comment]
I've tested this and threetenbp produces the same output as Java 17. This is probably in line with the definition from CLDR.

Closing as nothing to change.
