### ISSUE TITLE
Caused by: org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: America/Ciudad_Juarez

### ISSUE THREAD

**Issue by nehalsep7** [ThreeTen/threetenbp#178]
Caused by: org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: America/Ciudad_Juarez

**Comment by sschaap** [comment]
I'm guessing you're on Android? See my comment in #175 . The America/Ciudad_Juarez timezone was introduced in tzdb 2022g.

TL;DR Update your TTBP version to 1.6.5 or use the native `java.time.*` APIs instead (API 26+).
