### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by keesvandieren** [ThreeTen/threetenbp#191]
We're getting reported some vulnerabilities, as [visible per here](https://ossindex.sonatype.org/component/pkg:maven/org.threeten/threetenbp@1.6.9)

Is this already being picked up?

**Comment by jodastephen** [comment]
These are nonsense CVEs, generated by an AI bot. You should ignore them.

**Comment by keesvandieren** [comment]
Thank you!

**Comment by jodastephen** [comment]
[Official reference page](https://www.threeten.org/threetenbp/security.html).
