### ISSUE TITLE
Create qualified artifact without timezone data bundled.

### ISSUE THREAD

**Issue by JakeWharton** [ThreeTen/threetenbp#29]
Same use-case and motivations as https://github.com/JodaOrg/joda-time/issues/220.

**Comment by jodastephen** [comment]
Seems like it would be possible and reasonable.

**Comment by jodastephen** [comment]
Please review and test the no-tzdb branch
https://github.com/ThreeTen/threetenbp/commit/ed606c87fee81c953fa978d001e670cd21711072

**Comment by JakeWharton** [comment]
Will do in a few hours and report back! Thanks.

**Comment by JakeWharton** [comment]
Sorry been preparing a presentation all week (for tomorrow). I hope to play with this on Friday or the weekend!

**Comment by JakeWharton** [comment]
With #32 and the latest `no-tzdb` this seems to be fully working!
