### ISSUE TITLE
LeapSecondRules.dat unused?

### ISSUE THREAD

**Issue by JakeWharton** [ThreeTen/threetenbp#30]
This is generated by the compiler and embedded in the jar but appears unused as far as I can tell. Is it the case that it is unused? Or am I missing something here?

**Comment by jodastephen** [comment]
It was used at one point, but wasn't in the final Java 8 version. Can probably be removed from the backport.

**Comment by jodastephen** [comment]
Fixed by https://github.com/ThreeTen/threetenbp/commit/3c8321171e4fa2bb272cad1b39298eba179289f6
