### ISSUE TITLE
Consider TzdbZoneRulesProvider InputStream factory/ctor?

### ISSUE THREAD

**Issue by JakeWharton** [ThreeTen/threetenbp#32]
For the Android support, and in addition to the work towards #29, I need to load the `TZDB.dat` from an alternative location. Right now I have to duplicate the entirety of `TzdbZoneRulesProvider` in my own class but inside of the `org.threeten.bp.zone` package for access to `Ser` (and its transitive dependencies). It would be of great convenience if `TzdbZoneRulesProvider` had either a static factory or constructor overload that accepted an `InputStream` for reading of its data.

**Comment by jodastephen** [comment]
The branch has been rebased with a change that should address this, providing a public `load(URL)` method. You should be able to write a simple wrapper provider that wraps `TzdbZoneRulesProvider` now. You'll still need to register it in `META-INF/services/org.threeten.bp.zone.ZoneRulesProvider`.

**Comment by JakeWharton** [comment]
There needs to be a constructor overload for this as well, otherwise the no-arg constructor still attempts loading from resources.

**Comment by jodastephen** [comment]
Have a go with this change.

**Comment by JakeWharton** [comment]
Thanks. Unfortunately(!) the location from which we have to load the tzdb for memory efficiency on mobile isn't accessible via a URL. I thought I could coerce it to work, but it doesn't short of installing my own stream handler factory. I don't like that option because it prevents others from using the stream handler factory mechanism and in order to load the data I need to do it through an object with a lifecycle and don't want to tie it to an object instance that is effectively a process singleton.

So, would it be possible to switch the constructor to accept an `InputStream`? This will allow me to open the stream from the efficient location on Android as well as re-use the underlying version parsing and loading logic. I made a quick and haphazard refactor to support this locally and it indeed allows this to work.

**Comment by jodastephen** [comment]
Another attempt...

**Comment by JakeWharton** [comment]
Works great! Sorry for the thrashing on the API here, but I over-anticipated my ability to bend Android to my will.
