### ISSUE TITLE
No time-zone data files registered

### ISSUE THREAD

**Issue by IgorGanapolsky** [ThreeTen/threetenbp#33]
Hello,
I am devising unit tests on the JVM where I need to create an instance:
`        ZonedDateTime dateTimeWithZone = ZonedDateTime.now();`
However, I get an exception:
> org.threeten.bp.zone.ZoneRulesException: No time-zone data files registered

Please advise.

**Comment by jodastephen** [comment]
The time-zone rules are included in the jar file and should load automatically. Please ensure you are not using the "no-tzdb" jar file, which omits the time-zone data. Beyond that, you'd need to investigate yourself by debugging in `ZoneRulesProvider` and `TzdbZoneRulesProvider`.

**Comment by gmbutcher** [comment]
For anyone else still having this issue I was able to resolve it by updating my proguard rules: #12

**Comment by chanjungkim** [comment]
You need to register ThreetenBP in Application class with using 

```
    override fun onCreate() {
        super.onCreate()
        AndroidThreeTen.init(this)
    }
```

For example,

```
class MyApp: Application(){
    override fun onCreate() {
        super.onCreate()
        AndroidThreeTen.init(this)
    }
}
```

And you need to register the class on `manifests.xml`

```
    <application
        android:name=".MyApp"
        ...>
    </application>
```
