### ISSUE TITLE
IST timezone is not supported

### ISSUE THREAD

**Issue by solomax** [ThreeTen/threetenbp#37]
The following simple test shows IST time zone is supported by java7 and not supported by threetenbp :(
https://gist.github.com/solomax/818844adec1e8538123b

Stacktrace like this:

org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: IST
	at org.threeten.bp.zone.ZoneRulesProvider.getProvider(ZoneRulesProvider.java:178)
	at org.threeten.bp.zone.ZoneRulesProvider.getRules(ZoneRulesProvider.java:133)
	at org.threeten.bp.ZoneRegion.ofId(ZoneRegion.java:143)
	at org.threeten.bp.ZoneId.of(ZoneId.java:357)

Can it be addressed please :)

**Comment by jodastephen** [comment]
"IST" is not supported by java.time in Java 8 either.

Instead you have to pass the map of `SHORT_IDS` to the `ZoneId.of(String, Map)` method
http://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html#SHORT_IDS
http://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html#of-java.lang.String-java.util.Map-

**Comment by solomax** [comment]
Thanks for pointing this out!
Learn something new :)
