### ISSUE TITLE
LocalDate.ofEpochDay may return a wrong result

### ISSUE THREAD

**Issue by ummels** [ThreeTen/threetenbp#39]
`LocalDate.ofEpochDay(x)` sometimes returns a wrong or illegal result instead of throwing an exception for large values of `x`. For instance, `LocalDate.ofEpochDay(9223371671611556645L)` returns a date with a negative value for `d.getDayOfMonth()` instead of throwing a `DateTimeException`.

**Comment by ashwinbhaskar** [comment]
I too have experienced this issues on my android app but it seems to be limited to only certain models. This happens only on Moto g 3rd Gen

**Comment by RomainPiel** [comment]
I've had this issue for a few weeks in my Android app. It seems to only happen on Motorola devices running Android 6.0: http://stackoverflow.com/questions/35043000/motorola-devices-org-threeten-bp-datetimeexception-when-parsing-a-date-in-thre

**Comment by ummels** [comment]
For what it's worth, I can reproduce this bug on both Java SE 7 and 8 (64 bit edition, Mac OS X), so this bug is not specific to Android.

**Comment by benjamin-bader** [comment]
We're hitting this on Android; haven't yet identified a particular input value that causes the crash.
