### ISSUE TITLE
Suspicios-looking code in Instant

### ISSUE THREAD

**Issue by soc** [ThreeTen/threetenbp#41]
Sorry if this is a false alarm, but is it intentional that https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/Instant.java#L492 never returns any value, and always throws an exception, either a `DateTimeException` or an `UnsupportedTemporalTypeException`?

If this is intended, maybe it would help to add a short code comment?

**Comment by jodastephen** [comment]
The bug here is that it should always throw `UnsupportedTemporalTypeException`. Not a big bug though.
