### ISSUE TITLE
Make the time zone jar data loading pluggable to avoid Android performance problems

### ISSUE THREAD

**Issue by ZakTaccardi** [ThreeTen/threetenbp#45]
For reasons mentioned in the [android port](https://github.com/JakeWharton/ThreeTenABP), the loading of time zone information should be abstracted.

This way, a single library can be efficiently used across both java and android platforms.

My specific use case is that I have multiple pure java modules in my android project, and would like to share the API across both of them.

**Comment by JakeWharton** [comment]
This library is used on both platform. ThreeTenABP has a dependency on this project.
