### ISSUE TITLE
Decouple time zone loading to provide pure java support

### ISSUE THREAD

**Issue by ZakTaccardi** [ThreeTen/threetenbp#46]
Probably a big ask, but would be nice to make the initialization process work in both java or android world, while maintaining efficiency.

see sister issue: https://github.com/ThreeTen/threetenbp/issues/45

**Comment by JakeWharton** [comment]
It is already decoupled. You can provide your own implementation of `ZoneRulesProvider` using `ServiceLoader` or explicitly.

**Comment by ZakTaccardi** [comment]
My bad about this double issue, was supposed to be created on your android port. Either way it's irrelevant your library already does exactly what I want, thanks Jake
