### ISSUE TITLE
Possible license violations?

### ISSUE THREAD

**Issue by soc** [ThreeTen/threetenbp#52]
I just saw that a few of the recent commits linked to bugs in the OpenJDK bugtracker and code in the OpenJDK source repo.

Can you confirm that the code that ended up in this BSD-licensed repo has been contributed by the original author under this license? (I didn't look at the code as I'm very concerned about tainting myself by touching potentially license-incompatible code.)

**Comment by jodastephen** [comment]
The relevant commits have been force removed from master.

This [branch](https://github.com/ThreeTen/threetenbp/commit/28799e0aacfab4b8f01b528c089bd22a87094f0f) has been created with the code of the failing tests (new code written by me to exercise the issues). But if I can't fix them, perhaps you'd like to. Under strict rules, it requires someone who has not looked at the OpenJDK bug fixes.

**Comment by soc** [comment]
Thanks a lot, I haven't looked at the code, but I'm currently extremely busy with putting the finishing touches on my JS port and looking into the issues with compilation to amd64.
