### ISSUE TITLE
Backport bugs from OpenJDK

### ISSUE THREAD

**Issue by jodastephen** [ThreeTen/threetenbp#53]
This [branch](https://github.com/ThreeTen/threetenbp/commit/28799e0aacfab4b8f01b528c089bd22a87094f0f) contains test cases for three bugs reported at OpenJDK. I've written new tests but I can't really write the code that fixes them as I would be using knowledge of GPL code to do so. Looking for someone to take on this issue.

**Comment by toadzky** [comment]
What's the expected behavior for `Instant.toEpochMilli`? The documentation says it should throw an `ArithmeticException` if it can't fit into a `long`, which is what it does on the test.

**Comment by jodastephen** [comment]
In the test case, all four additional values are valid millis (Long.MAX, Lon.MAX - 1, Long.MIN, Long.MIN + 1). Need to look at behavior after 1970 vs before 1970

**Comment by toadzky** [comment]
I've got the tests for `truncatedTo` fixed, but I'm still not sure how to fix the `toEpochMilli` part. I'll keep working on it. Should I open a PR now or wait until all of them are fixed?

**Comment by jodastephen** [comment]
Separate PR would be great. Think about whether milliseconds less than zero
needs different logic.

**Comment by marschall** [comment]
I gave the toEpochMilli a shot in #56. It's not the most beautiful or clever code.

**Comment by tprochazka** [comment]
It's relly sad, that it's called OpenJava a is neccesary to rewrite everything to use it on older Java. But probably use Android Java under Apache Licence would be also way.

**Comment by JakeWharton** [comment]
Android uses OpenJDK for java.time

**Comment by raupachz** [comment]
What is the current state of this issue? Would like to look into this issue, but I feel a bit lost about where to start. Are all three bugs still open?

**Comment by jodastephen** [comment]
Its been a while, so I don't know for sure. I'd recommend rebasing the [branch](https://github.com/ThreeTen/threetenbp/commit/28799e0aacfab4b8f01b528c089bd22a87094f0f) with tests to HEAD and see if it still fails.

**Comment by raupachz** [comment]
Looks like this issue is solved. To my understanding this is already in master. 

```
git checkout master
git checkout -b issue53 28799e0aacfab4b8f01b528c089bd22a87094f0f
git rebase master
mvn verify
```

All tests pass. 

```
commit 5dda16e66ff30af443e307fe7b51e01a7951e852 (HEAD -> issue53, upstream/master, origin/master, origin/HEAD, master)
```
