### ISSUE TITLE
How to deserialize ThreeTen LocalDateTime in Retrofit?

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [ThreeTen/threetenbp#59]
I'm trying to deserialise this class in Retrofit:

data class Measurement(val id: Long, val value: Float, val dateTime: LocalDateTime, val trashCanId: Long) : Parcelable {
    companion object {
        @JvmField val CREATOR: Parcelable.Creator<Measurement> = object : Parcelable.Creator<Measurement> {
            override fun createFromParcel(source: Parcel): Measurement = Measurement(source)
            override fun newArray(size: Int): Array<Measurement?> = arrayOfNulls(size)
        } 
    } 
 
    constructor(source: Parcel) : this(source.readLong(), source.readFloat(), source.readSerializable() as LocalDateTime, source.readLong()) 
 
    override fun describeContents() = 0 
 
    override fun writeToParcel(dest: Parcel?, flags: Int) { 
        dest?.writeLong(id) 
        dest?.writeFloat(value) 
        dest?.writeSerializable(dateTime) 
        dest?.writeLong(trashCanId) 
    } 
 
} 
As you can see, I'm using LocalDateTime, it's from ThreeTen. Well, I receive this from my server

    {
        "id": 1,
        "value": 50.6,
        "dateTime": {
          "hour": 2,
          "minute": 6,
          "second": 9,
          "nano": 0,
          "dayOfYear": 308,
          "dayOfWeek": "THURSDAY",
          "month": "NOVEMBER",
          "dayOfMonth": 3,
          "year": 2016,
          "monthValue": 11,
          "chronology": {
            "id": "ISO",
            "calendarType": "iso8601"
          }
        }
      }
Well, but my dateTime is always Null so I believe that Retrofit doesn't know how parse the Data, or am I missing something?

Is there any good workaround?

**Comment by JakeWharton** [comment]
The correct location for this question is StackOverflow, where you've
already asked it:
http://stackoverflow.com/questions/40456566/how-to-deserialize-threeten-localdatetime-in-retrofit
