### ISSUE TITLE
Timestamp/Time/Date is currently unsuitable for LocalDateTime/LocalDate/LocalTime

### ISSUE THREAD

**Issue by consp1racy** [ThreeTen/threetenbp#60]
Issue:
Currently LocalDateTime is fed to Timestamp using (years, month, day, hours, minutes, seconds, nanos) constructor. This constructor calls through to Date constructor which uses *current time zone* to convert individual fields to millis. This results in wrong value being stored when working in non-UTC time zone. Similar approach (using individual fields) is used and issue encountered on the way back.

Solution:
LocalDateTime has to be converted to epoch millis/nanos *before* feeding it to Timestamp constructor. Then only `getTime()` can be called to safely retrieve original value.

**Comment by jodastephen** [comment]
I assume this is referring to `DateTimeUtils` in the backport. The code in that class mirrors the code in Java 8. As such, it is "correct" for the backport.
