### ISSUE TITLE
LocalDate.ofEpochDate() should specify the TimeZone used

### ISSUE THREAD

**Issue by niclash** [ThreeTen/threetenbp#61]
IIUIC, the LocalDate.ofEpochDay() uses UTC time zone for computing the localdate and not the system default timezone, nor does it allow a time zone to be provided.

This is probably an oversight either in the thinking (no days are not time zone dependent - wrong) or oversight in documenting what is exactly happening.

I am simply suggesting that the Javadoc is updated to state that UTC is used, which could go into a patch release.

**Comment by jodastephen** [comment]
This is a misunderstanding. As per the docs, [EPOCH_DAY](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/ChronoField.html#EPOCH_DAY) is a _local_ value, where no time-zone is involved. As such, conversion from a local epoch day to a `LocalDate` requires no time-zone (they are using the same local time-line). UTC is not relevant to the conversion, thus not mentioned.
