### ISSUE TITLE
DateTimeFormatter not properly formatting month and day of week string

### ISSUE THREAD

**Issue by tir38** [ThreeTen/threetenbp#62]
I'm using ThreeTen on Android via [ThreeTenABP](https://github.com/JakeWharton/ThreeTenABP). I'm trying to format a ZonedDateTime as `Tuesday, March 19`. But I'm only ending up with `Tue, 3 19`. I believe this is different than #50. It's happening on all devices, and the actual date is correct, just the formatting is wrong.

I'm pretty sure I'm following the [formatting string guidelines](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) correctly.

```
DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("EEEE, MMMM d");
String dateString = zonedDateTime.format(dateFormat);
```

The bizarre part is that when I unit test this code it works fine, but running on an actual Android device truncates day of the week and uses integer for month.

**Comment by jodastephen** [comment]
I'm afraid as I don't use the library on Android I don't have anything to add. Ultimately, this will only happen if it can't find the text for the relevant value.

**Comment by tir38** [comment]
Can you clarify what you mean by "this will only happen if it can't find the text for the relevant value." I can try testing different values/configurations.

**Comment by jodastephen** [comment]
The code to find the text is [here](https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/format/SimpleDateTimeTextProvider.java#L66). If text is not found, [the numeric value is output as a fallback](https://github.com/ThreeTen/threetenbp/blob/master/src/main/java/org/threeten/bp/format/DateTimeFormatterBuilder.java#L2852).

**Comment by pamalyshev** [comment]
@tir38, I've made a test for this in https://github.com/pamalyshev/lazythreetenbp/commit/6866656607ed4c91dc32e9b06fc8351f76543ca8
Could you build it and run all Instrumentation tests on devices on which you have that problem?
