### ISSUE TITLE
no-tzdb should exclude ServiceLoader code from ZoneRulesProvider

### ISSUE THREAD

**Issue by mmallozzi** [ThreeTen/threetenbp#63]
When the timezone DB isn't included in the JAR, the code to look for it and load it with ServiceLoader should be removed from the static initializer block of ZoneRulesProvider. Apparently ServiceLoader is extremely slow on Android even if there are no implementations loaded (since no-tzdb already handles removing the META-INF entry), and it's not needed when the code isn't bundled with a tzdb.

I was trying to figure out some Maven incantation to exclude this version of the class and include an alternate version that removes the static initializer block, but I've never used Maven before so I'm lost :)

**Comment by hzsweers** [comment]
Make a pull request?

**Comment by mmallozzi** [comment]
I will once I figure out how to use Maven, but I wanted to file this for now in case someone more knowledgeable than me knows how to configure this really easily.

**Comment by jodastephen** [comment]
While I understand the problem, removing the service loader code would change the behaviour of the library, as the user could include their own provider, which would then not be loaded.

**Comment by jodastephen** [comment]
One possible choice is to add a command line flag. The flag would be checked in an if statement around this code. If this appeals to someone, and it works, feel free to raise a PR.

**Comment by mmallozzi** [comment]
Yeah, I was hoping to find a way to remove the serve loader code just for the no-tzdb build variant and keep it in for the default JAR, as the no-tzdb JAR wouldn't have anything to load through the service loader. Or can applications using the no-tzdb JAR add entries to their own META-INF which would be picked up by the library code? In that case, yes it wouldn't make sense to remove it even for the no-tzdb JAR.

I'm trying to sort out how to get a command line flag working here. In terms of communicating with the library though, since this ServiceLoader code is in a static initializer block for ZoneRulesProvider, the most straightforward approach I see is to create another class outside ZoneRulesProvider, say `ThreeTenBPConfig`, which has a static flag `useServerLoader` that defaults to true, but which can be set to false by a calling application/library before any other ThreeTenBP code is called, lest it accidentally uses something in ZoneRulesProvider and triggers the static initializer before this flag is set. Then the static block can be a no-op when it is eventually invoked, according to `ThreeTenBPConfig.useServiceLoader`.

Unfortunately this, like any static state, can be an issue in complicated applications where one part of code wants to disable the service loader but another (or even a third party library used by the application) registers something in its META-INF expecting to make use of it. But in practice I don't know how often this would come up.

**Comment by mmallozzi** [comment]
PR here: https://github.com/ThreeTen/threetenbp/pull/64

**Comment by mmallozzi** [comment]
Better PR here: https://github.com/ThreeTen/threetenbp/pull/65

**Comment by jodastephen** [comment]
Fixed by https://github.com/ThreeTen/threetenbp/commit/38f6889c8ff0e5309540dde0d4b94e6de7dc634a

**Comment by hzsweers** [comment]
Thanks @jodastephen!
