### ISSUE TITLE
Islamic date is not same as Threeten

### ISSUE THREAD

**Issue by sw926** [ThreeTen/threetenbp#66]
```
org.threeten.bp.chrono.HijrahDate hijrahDate = org.threeten.bp.chrono.HijrahDate.now();
System.out.println(hijrahDate);

HijrahDate date = HijrahDate.now();
System.out.println(date);
```
outputs:
```
Hijrah-umalqura AH 1438-08-15
Hijrah-umalqura AH 1438-08-16
```

**Comment by tynn** [comment]
I think this is still an issue related to the length of months.

Today I found `Hijrah-umalqura AH 1442-01-30` which should not exist.

For me it seems like `HijrahDate.MONTH_LENGTH` is too much of a simplification as this seems to change year to year.

@jodastephen maybe this issue should be reopened.
