### ISSUE TITLE
Allow custom DateTimeTextProvider to be set as default

### ISSUE THREAD

**Issue by pamalyshev** [ThreeTen/threetenbp#69]
Android 2.3 and later supports stand-alone text forms for months and days of weeks.
Also Android 4.3 and later supports narrow text forms.
These text forms can be acquired by using SimpleDateFormat with appropriate patterns.

To take advantage of these Android features we need to be able to set a custom implementation of DateTimeTextProvider as default.

Current implementation of DateTimeTextProvider.getInstance() returns a new instance every time. Is that intentional?

**Comment by jodastephen** [comment]
The provider cannot be replaced in JDK8, so technically this is extending the backport beyond the functionality of the original library.

**Comment by jodastephen** [comment]
There may be a way to do this, but the PR broke Travis builds.

**Comment by jodastephen** [comment]
Found a way to make this work. The code looks different but should have the desired effect.
