### ISSUE TITLE
how to exclude the TZDB.dat

### ISSUE THREAD

**Issue by blackberry2016** [ThreeTen/threetenbp#72]
how to exclude the TZDB.dat , [because i use another way to load it](https://github.com/JakeWharton/ThreeTenABP)

**Comment by pamalyshev** [comment]
You don't need to depend on ThreeTenBP directly when you depend on ThreeTenABP.
ThreeTenABP depends on "no-tzdb" artifact, and uses its own TZDB.dat stored in the assets.
Just follow instructions from ThreeTenABP's readme.

**Comment by blackberry2016** [comment]
My problem is the #71
