### ISSUE TITLE
Why ZonedDateTime.parse ignores the zone offset ?

### ISSUE THREAD

**Issue by pithu** [ThreeTen/threetenbp#73]
When parsing a ZonedDateTime with the default formatter ISO_ZONED_DATE_TIME and passing an iso string with an offset and a zone region, the offset is ignored. 

eg in the following example the offset always resolves to `-07:00` regardless what offset is passed to the parser.

```
offset1 = ZonedDateTime.parse("2017-11-05T01:00:00-06:00[America/Los_Angeles]")
    .getOffset() // -07:00
offset2 = ZonedDateTime.parse("2017-11-05T01:00:00-07:00[America/Los_Angeles]")
    .getOffset() // -07:00
offset3 = ZonedDateTime.parse("2017-11-05T01:00:00-08:00[America/Los_Angeles]")
    .getOffset() // -07:00
```

Shouldn’t `offset3` resolve to `-08:00`, because it is an dst overlap situation?
And because the default formatter is in STRICT mode, wouldn’t we expect that an exception is thrown for the line with `offset1`?

It seems the behavior changes in jdk9, do you know why? With jdk9-ea the offset3 is what I expect, but an invalid offset is still ignored. 

Same example as above returns for jdk9-ea+170

```
offset1 = ZonedDateTime.parse("2017-11-05T01:00:00-06:00[America/Los_Angeles]")
    .getOffset() // -07:00
offset2 = ZonedDateTime.parse("2017-11-05T01:00:00-07:00[America/Los_Angeles]")
    .getOffset() // -07:00
offset3 = ZonedDateTime.parse("2017-11-05T01:00:00-08:00[America/Los_Angeles]")
    .getOffset() // -08:00 <
```

**Comment by jodastephen** [comment]
This is the JDK bug: https://bugs.openjdk.java.net/browse/JDK-8066982
If it also affects the backport, then that needs fixing.
