### ISSUE TITLE
TemporalAccessor API different from Java8

### ISSUE THREAD

**Issue by msrd0** [ThreeTen/threetenbp#78]
For those that are trying to derive their own class from `TemporalAccessor` might notice that in Java8 (see the source code [here](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/time/temporal/TemporalAccessor.java)) the [`get`](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/TemporalAccessor.html#get-java.time.temporal.TemporalField-), [`query`](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/TemporalAccessor.html#query-java.time.temporal.TemporalQuery-) and [`range`](https://docs.oracle.com/javase/8/docs/api/java/time/temporal/TemporalAccessor.html#range-java.time.temporal.TemporalField-) methods are default methods means one does not have to override them. However, use ThreeTenBP I have to override those methods.

I know that the interface is marked as a framework-level interface, however reading the javadoc makes me believe that one does not necessarily want to avoid users creating subtypes but rather make them use specific types instead of generic ones. Please correct me if I'm wrong or point me to a better solution if there is one. The reason why I'm trying to inherit from `TemporalAccessor` is because [`DateTimeFormatter.format`](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#format-java.time.temporal.TemporalAccessor-) takes a `TemporalAccessor` as an argument.

**Comment by jodastephen** [comment]
There are a set of abstract classes that simulate the default interface methods of Java 8:
https://github.com/ThreeTen/threetenbp/tree/master/src/main/java/org/threeten/bp/jdk8
