### ISSUE TITLE
Question: is "LocalDate.hashCode" implementation unique?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ThreeTen/threetenbp#81]
I need to know this in order to use it for identification of items. Each item has a different LocalDate (of a different day) than the other, and I need an integer/long that identifies the LocalDate uniquely.

**Comment by jodastephen** [comment]
No, not unique. You need a `long` to make it unique.

**Comment by AndroidDeveloperLB** [comment]
How can I do it?
Will just converting the code of what's in `hashCode` into long be enough?

**Comment by AndroidDeveloperLB** [comment]
ok wrote about it somewhere else
