### ISSUE TITLE
How to get a unique value out of LocalDate instance?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ThreeTen/threetenbp#82]
I need to differentiate between LocalDate instances by a long/int value.
This is useful in this case, for example:
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html#getItemId(int)

I was told that hashCode isn't good enough:
https://github.com/ThreeTen/threetenbp/issues/81

What can I do instead?

**Comment by AndroidDeveloperLB** [comment]
Maybe like this:


```
fun LocalDate.getUniqueId(): Long {
    val yearValue = year //4 bytes = 32 bit
    val monthValue = monthValue //2 bytes = 16 bits
    val dayValue = dayOfMonth //2 bytes= 16 bits
   // in Java, it's : (long) yearValue + (monthValue << 32) + (dayValue <<48)
    val result = yearValue.toLong() + (monthValue shl 32) + (dayValue shl 48)
    return result
}
```

?

**Comment by MenoData** [comment]
Why not using [toEpochDay()](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html#toEpochDay--)?

**Comment by AndroidDeveloperLB** [comment]
Should usually not be an issue (and probably in my case too) , but what if it's before 1970?
If the answer is that it will be negative, that's bad choice for me. I have to have it always positive.

**Comment by AndroidDeveloperLB** [comment]
But I wonder something: is my previous code also ok?

**Comment by AndroidDeveloperLB** [comment]
@jodastephen Why close this? Is it ok or not?

**Comment by AndroidDeveloperLB** [comment]
I think this is better, seeing that LocalDate actually has a min and max values:

`fun LocalDate.getUniqueId(): Long = toEpochDay() - LocalDate.MIN.toEpochDay()`

**Comment by MenoData** [comment]
@AndroidDeveloperLB I think most people expect clean Java syntax here (is that kotlin or scala or something else). And why do you not post your questions to stackoverflow site where you also have an account? The audience and support for code discussions would be much better. This is also true for some of your other questions like "Hebrew calendar in Joda-Time" or #84 or your questions about other android-specific topics etc.

**Comment by AndroidDeveloperLB** [comment]
It's Kotlin, and since the context is Android, it's fully supported on Android development, even if you write in Java.

Here's Java code that I write directly here :

```
public static long getUniqueId(LocalDate localDate){
    return localDate.toEpochDay()-LocalDate.MIN.toEpochDay();
}

```
