### ISSUE TITLE
RFC 1123 Formatter does not correctly handle certain valid RFC dates

### ISSUE THREAD

**Issue by magneticflux-** [ThreeTen/threetenbp#83]
[RFC 822 reference](https://tools.ietf.org/html/rfc822#section-5)
[RFC 1123 reference](https://tools.ietf.org/html/rfc1123#page-56)

The valid RFC 1123 date `Fri, 18 May 2012 00:00:00 EST` causes a parser exception. There is a comment in the source code that states `// should handle UT/Z/EST/EDT/CST/CDT/MST/MDT/PST/MDT`, however that support was never included.

**Comment by jodastephen** [comment]
The backport matches the code in the JDK, which also does not support `EST` and similar.
