### ISSUE TITLE
Publish sources artifact for the no-tzdb binary

### ISSUE THREAD

**Issue by marcin-kozinski** [ThreeTen/threetenbp#86]
Would it be possible to publish an artifact with sources matching the binary with `no-tzdb` classifier? I know technically the sources are the same. But when using IntelliJ IDEA (or Android Studio) the sources are not correctly picked up. The IDE fails with message:

> Sources not found: Sources for 'threetenbp-1.3.6-no-tzdb.jar' not found

So when consuming the `no-tzdb` version of the library in IntelliJ IDEA/Android Studio we don't get the benefit of Javadocs or looking at the implementation.

See: https://github.com/JakeWharton/ThreeTenABP/issues/55

**Comment by bernaferrari** [comment]
![image](https://user-images.githubusercontent.com/351125/56106105-f459f980-5f15-11e9-9561-7420f9dd75d5.png)
I'm still having this problem on ThreeTenABP. Did that commit fix things for you, @marcin-kozinski ?

**Comment by marcin-kozinski** [comment]
Hey @bernaferrari, sorry for the late reply (I'm on parental leave). Just tried it on a new project using ThreeTenABP 1.2.0 in Android Studio 3.5 Canary 13 and it sort of worked. When I first Cmd+clicked into `LocalDateTime` I saw the same thing as your screen shot shows. But the "Download Sources" button worked for me — it automatically downloaded the sources (without asking me for location or anything) and reloaded the source file instead of the decompiled class file.

If this doesn't work for you the first thing I would try is updating ThreeTenABP — you have to be on a version that picked up the newer ThreeTenBP which published the sources (I don't think Stephen went back to publish sources for past releases).
