### ISSUE TITLE
Unknown TimeZone ID : Asia/Yangon

### ISSUE THREAD

**Issue by vincent-paing** [ThreeTen/threetenbp#87]
The app crashes on setting the timezone to Asia/Yangon. Here's the log

`FATAL EXCEPTION: main Process: <my_app_id>, PID: 1462 org.threeten.bp.zone.ZoneRulesException: Unknown time-zone ID: Asia/Yangon at org.threeten.bp.zone.ZoneRulesProvider.b(ZoneRulesProvider.java:1178) at org.threeten.bp.ZoneRegion.a(ZoneRegion.java:143) at org.threeten.bp.ZoneId.a(ZoneId.java:1357)`

**Comment by kaungmyatlwin** [comment]
+1

It's a huge issue crashing on big apps like Reddit Mobile.

**Comment by jodastephen** [comment]
Using v1.3.6 of threetenbp on a standard JDK has no problem with this time-zone. I assume you are using Android, and probably not using the standard `threetenbp-1.3.6.jar` file, so I can't really help further.
