### ISSUE TITLE
org.threeten.bp.format.DateTimeParseException

### ISSUE THREAD

**Issue by ArunPandiyan** [ThreeTen/threetenbp#89]
I'm using two phones lenovo with 7.1.2 and samsung with 5.1.1 Android versions.
I'm trying to parse like this
```
StartTime = "12.20 AM"
DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm a");
LocalTime startTime = LocalTime.parse(StartTime, formatter);
```
in samsung it throws following error.
`org.threeten.bp.format.DateTimeParseException: Text '12:20 am' could not be parsed at index 6`

then i tried to put string to lowercase. It just works. But earlier in lenovo which was working fine now throws the same error. What is happening?

**Comment by jodastephen** [comment]
This would probably work:

    new DateTimeFormatterBuilder()
                .parseCaseInsensitive()
                .appendPattern("hh:mm a")
                .toFormatter()

**Comment by ArunPandiyan** [comment]
Yes, that saved me!

**Comment by osrl** [comment]
Hello @jodastephen . I also get the same error. Her is my exception:
`org.threeten.bp.format.DateTimeParseException: Text '08am' could not be parsed at index 2`

here is the code I use:
```
val TIME_FORMATTER = DateTimeFormatterBuilder()
                .parseCaseInsensitive()
                .appendPattern("hha")
                .toFormatter()!!

LocalTime.parse("08am", TIME_FORMATTER)
```

The thing is, my tests succeeds with the same formatter :/

```
@Test
    fun localTime_isCorrect() {
        val times = listOf(
                "08am",
                "09am",
                "10am",
                "11am",
                "12pm",
                "01pm",
                "02pm",
                "03pm",
                "04pm",
                "05pm",
                "06pm"
        )

        for ((i, timeString) in times.withIndex()) {
            val expectedTime = LocalTime.of(i + 8, 0)
            val time = LocalTime.parse(timeString, DateUtils.TIME_FORMATTER)
            Assert.assertEquals("error on $timeString", expectedTime, time)
        }
    }
```
