### ISSUE TITLE
Wrong timezone parsing

### ISSUE THREAD

**Issue by Diolor** [ThreeTen/threetenbp#90]
System:
               
```
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)
```

For this code:

```java
    String dateString = "2015,7,21,0,0,0,GMT+02:00";
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy,M,d,H,m,s,z", Locale.US);
		ZonedDateTime parsed = ZonedDateTime.parse(dateString, formatter);
		System.out.println("Parsed: " + parsed);
```

Output is:

    2015-07-21T00:00+03:00[Asia/Famagusta]

Expectation:

    2015-07-21T00:00+02:00[Etc/GMT-2]

Is it happening only here or is reproducible to you?

**Comment by Diolor** [comment]
In `1.8.0_152-release` and below the issue is not appearing.

**Comment by CDehning** [comment]
Hey guys, when are you planning to release this fix?

Thanks for your help!

**Comment by jodastephen** [comment]
v1.3.7 released
