### ISSUE TITLE
Inaccurate birthday computation

### ISSUE THREAD

**Issue by ralphgabrielle** [ThreeTen/threetenbp#96]
As of today, its November 13, 2018.

I set a birthdate of November 14, 2000 which should be 17 years old (will be 18 tomorrow), but Period.between returns 18.

Is it just basing on number of years not the actual days (including leap years.)

Thanks, I would appreciate any help or suggestion and/or any mistake on my end.

Currently this is my implementation just same with what we have on official Java8 implementation.

`       org.threeten.bp.LocalDate birthDate = org.threeten.bp.LocalDate.of(calendar.get(Calendar.YEAR), calendar.get(Calendar.MONTH), calendar.get(Calendar.DAY_OF_MONTH));
       org.threeten.bp.LocalDate today = org.threeten.bp.LocalDate.now();
       org.threeten.bp.Period between = org.threeten.bp.Period.between(birthDate, today);
       int ageInYears = between.getYears();`

Thanks,
Ralph

**Comment by sschaap** [comment]
Both the Java 8 implementation (openjdk version "1.8.0_191-1-redhat") and threetenbp (v1.3.8) calculate the period between `November 14th, 2000` and `November 13th, 2018` to be `P17Y11M30D` with a `years` component equal to `17`. Perhaps your value of `calendar` is erroneous. It suggests the use of `java.util.Calendar` which is notoriously hard to use right as well as unnecessary when `java.time` or TTBP is available.

Recommend issue be closed.

```
package com.example;

public class AgeTest {
    
    public static void main(String[] args) {
        org.threeten.bp.LocalDate bpBirthDate = org.threeten.bp.LocalDate.of(2000, 11, 14);
        org.threeten.bp.LocalDate bpRefDate = org.threeten.bp.LocalDate.of(2018, 11, 13);
        org.threeten.bp.Period bpPeriod = org.threeten.bp.Period.between(bpBirthDate, bpRefDate);
        System.out.println("bpPeriod = " + bpPeriod);
        System.out.println("bpPeriod.years = " + bpPeriod.getYears());
    
        java.time.LocalDate jBirthDate = java.time.LocalDate.of(2000, 11, 14);
        java.time.LocalDate jRefDate = java.time.LocalDate.of(2018, 11, 13);
        java.time.Period jPeriod = java.time.Period.between(jBirthDate, jRefDate);
        System.out.println("jPeriod = " + jPeriod);
        System.out.println("jPeriod.years = " + jPeriod.getYears());
    }
}
```

Outputs:

```
bpPeriod = P17Y11M30D
bpPeriod.years = 17
jPeriod = P17Y11M30D
jPeriod.years = 17
```
