### ISSUE TITLE
incorrect result of dayOfWeek.getDisplayName(TextStyle.NARROW, Locale.getDefault())

### ISSUE THREAD

**Issue by VinsonGuo** [ThreeTen/threetenbp#97]
Thanks your library help to develop, but I find an exception when I used "LocalDate.now().dayOfWeek.getDisplayName(TextStyle.NARROW or STANDALONG, Locale.getDefault())". My Location and device region is China, System language is Chinese. For example, today is Wednesday, the correct result should be “三” (third) instead of "星" and other day's result is "星" which should be "一、二、三...". When I set locale to US, the result is "W", it's right.

**Comment by jodastephen** [comment]
The text that is used varies by JDK version, because it uses the underlying JDK data. It is unlikely that much can be done to fix this.

**Comment by sschaap** [comment]
@VinsonGuo From your avatar I'd guess you're running this on an Android device.

Judging from my own (extensive) Android experience, many devices have issues with localized text. If localization for English works as expected, then it is most likely that (as @jodastephen notes) the platform-provided localizations are incorrect. I would recommend that you try to reproduce the issue on either a proper JDK environment, or on another Android device. In the latter case, try a flagship device of a top-tier manufacturer; there tends to be more attention to detail in the ROMs for those.

**Comment by VinsonGuo** [comment]
@jodastephen @sschaap Thanks for your explain, I forgot to explain my running env. I use jdk1.8.0_77 and my targetSdkVersion of Android is 26. I had resolved it by this code:
String name;
            switch (date.getDayOfWeek().getValue()) {
                case 1:
                    name = "一";
                    break;
                case 2:
                    name = "二";
                    break;
                case 3:
                    name = "三";
                    break;
                case 4:
                    name = "四";
                    break;
                case 5:
                    name = "五";
                    break;
                case 6:
                    name = "六";
                    break;
                default:
                    name = "日";
                    break;
            }
            return name;
but I think it's not a best way to solve it.

**Comment by VinsonGuo** [comment]
@keithharris 
I have traced this issue. It's seem not jdk's bug because "org.threeten.bp.format.SimpleDateTimeTextProvider"'s  field variable valueTextMap have something wrong when Locale.lauguage="zh" and Locale.region="CN".

![image](https://user-images.githubusercontent.com/15139302/48707316-07ec8700-ec3a-11e8-9fd2-23dc506b2af0.png)

There shouldn't use substring(0, 1) when locale is "CN", you should substring last char.
![image](https://user-images.githubusercontent.com/15139302/48707706-40d92b80-ec3b-11e8-9e82-6879c3ea1a45.png)

**Comment by jodastephen** [comment]
I'd appreciate confirmation that this branch is correct before merging: https://github.com/ThreeTen/threetenbp/commit/025bd8f6a27d4be93f091c8b9d8a2831e1ed1fc7 (topic/narrow-text)

**Comment by ouchadam** [comment]
@jodastephen the issue occurs for the "ar" locale as well (and potentially all non latin languages judging from your commit) 

```kotlin
@Test
fun `print AR narrow days`() {
  DateFormatSymbols.getInstance(Locale("ar")).shortWeekdays.forEach { println(it) }

  DayOfWeek.values().map { it.getDisplayName(TextStyle.NARROW, Locale("ar")) }.forEach { println(it) }
}
```
ح
ن
ث
ر
خ
ج
س

ا
ا
ا
ا
ا
ا
ا
```

**Comment by gabrielittner** [comment]
Hebrew is also affected by this

**Comment by jodastephen** [comment]
Would someone like to take the branch and enhance it for other languages?
https://github.com/ThreeTen/threetenbp/commit/025bd8f6a27d4be93f091c8b9d8a2831e1ed1fc7

**Comment by gabrielittner** [comment]
I'd be happy to pick it up, but I don't speak any of the affected languages. As soon as I've got a bit of time I will prepare a PR, to at least get this into a state where it could be reviewed.

**Comment by ouchadam** [comment]
google calendar appears to be a good source of single character days
